
package com.ruoyi.wsdl.esbService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PushMessageService", targetNamespace = "http://www.jscb.com.cn/mxmop/type/PushMessageService/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PushMessageService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.kibo.service.PushMessageResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public PushMessageResponse pushMessage(
            @WebParam(name = "arg0", partName = "arg0")
                    PushMessageRequest arg0);

}
