
package com.ruoyi.wsdl.esbService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PushMessageServiceSoapBindingQSService", targetNamespace = "http://www.jscb.com.cn/mxmop/type/PushMessageService/", wsdlLocation = "file:/C:/Users/\u9ec4\u6210\u535a/Desktop/wwww/PushMessageServiceProxyService.wsdl")
public class PushMessageServiceSoapBindingQSService
    extends Service
{

    private final static URL PUSHMESSAGESERVICESOAPBINDINGQSSERVICE_WSDL_LOCATION;
    private final static WebServiceException PUSHMESSAGESERVICESOAPBINDINGQSSERVICE_EXCEPTION;
    private final static QName PUSHMESSAGESERVICESOAPBINDINGQSSERVICE_QNAME = new QName("http://www.jscb.com.cn/mxmop/type/PushMessageService/", "PushMessageServiceSoapBindingQSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            //url = new URL("http://88.0.89.101:8001/EsbService/PushMessageServiceProxyService");
            url = new URL("http://66.1.43.14:8001/EsbService/PushMessageServiceProxyService");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUSHMESSAGESERVICESOAPBINDINGQSSERVICE_WSDL_LOCATION = url;
        PUSHMESSAGESERVICESOAPBINDINGQSSERVICE_EXCEPTION = e;
    }

    public PushMessageServiceSoapBindingQSService() {
        super(__getWsdlLocation(), PUSHMESSAGESERVICESOAPBINDINGQSSERVICE_QNAME);
    }

    public PushMessageServiceSoapBindingQSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUSHMESSAGESERVICESOAPBINDINGQSSERVICE_QNAME, features);
    }

    public PushMessageServiceSoapBindingQSService(URL wsdlLocation) {
        super(wsdlLocation, PUSHMESSAGESERVICESOAPBINDINGQSSERVICE_QNAME);
    }

    public PushMessageServiceSoapBindingQSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUSHMESSAGESERVICESOAPBINDINGQSSERVICE_QNAME, features);
    }

    public PushMessageServiceSoapBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PushMessageServiceSoapBindingQSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PushMessageService
     */
    @WebEndpoint(name = "PushMessageServiceSoapBindingQSPort")
    public PushMessageService getPushMessageServiceSoapBindingQSPort() {
        return super.getPort(new QName("http://www.jscb.com.cn/mxmop/type/PushMessageService/", "PushMessageServiceSoapBindingQSPort"), PushMessageService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PushMessageService
     */
    @WebEndpoint(name = "PushMessageServiceSoapBindingQSPort")
    public PushMessageService getPushMessageServiceSoapBindingQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.jscb.com.cn/mxmop/type/PushMessageService/", "PushMessageServiceSoapBindingQSPort"), PushMessageService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUSHMESSAGESERVICESOAPBINDINGQSSERVICE_EXCEPTION!= null) {
            throw PUSHMESSAGESERVICESOAPBINDINGQSSERVICE_EXCEPTION;
        }
        return PUSHMESSAGESERVICESOAPBINDINGQSSERVICE_WSDL_LOCATION;
    }

}
